const orderDate = new Date();
const occurDate = new Date('2024-04-01');
const orderList = [
  {
    id: '#1',
    customerName: 'truong',
    groom: 'Le Quang Truong',
    bride: 'Truong Quang Le',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'noon',
    status: 'deposit',
    payMethod: 'cash',
    orderDate: orderDate.toLocaleDateString(),
    occurDate: occurDate.toLocaleDateString(),
    totalTable: 100,
    pricePerTable: 200,
    serviceFee: 2000,
    total: 100000,
    deposit: 100,
    extraFee: 0,
    remainder: 990000,
    isPenaltyMode: false,
    paidDate: null,
  },
  {
    id: '#2',
    customerName: 'Canh & Quy',
    groom: 'Canh',
    bride: 'QUy',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'noon',
    status: 'paid',
    payMethod: 'cash',
    orderDate: orderDate.toLocaleDateString(),
    occurDate: occurDate.toLocaleDateString(),
    paidDate: new Date(),
    totalTable: 100,
    pricePerTable: 200,
    serviceFee: 2000,
    total: 100000,
    deposit: 100,
    extraFee: 0,
    remainder: 990000,
    isPenaltyMode: false,
  },
  {
    id: '#3',
    customerName: 'Pham Doan Canh & Le Tan Hoa',
    groom: 'Pham Doan Canh',
    bride: 'Le Tan Hoa',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    status: 'deposit',
    payMethod: 'cash',
    orderDate: orderDate.toLocaleDateString(),
    occurDate: occurDate.toLocaleDateString(),
    paidDate: new Date(),
    totalTable: 100,
    pricePerTable: 200,
    serviceFee: 2000,
    total: 100000,
    deposit: 100,
    extraFee: 0,
    remainder: 990000,
    isPenaltyMode: false,
  },
  {
    id: '#4',
    customerName: 'quy',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'deposit',
  },
  {
    id: '#5',
    customerName: 'hoa',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'deposit',
  },
  {
    id: '#6',
    customerName: 'trule',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'paid',
  },
  {
    id: '#1r24id',
    customerName: 'trule',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'paid',
  },
  {
    id: '#1r24id',
    customerName: 'trule',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'paid',
  },
  {
    id: '#1r24id',
    customerName: 'trule',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'paid',
  },
  {
    id: '#1r24id',
    customerName: 'trule',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'paid',
  },
  {
    id: '#1r24id',
    customerName: 'trule',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'paid',
  },
  {
    id: '#1r24id',
    customerName: 'trule',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'paid',
  },
  {
    id: '#1r24id',
    customerName: 'trule',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'paid',
  },
  {
    id: '#1r24id',
    customerName: 'trule',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'paid',
  },
  {
    id: '#1r24id',
    customerName: 'trule',
    phone: '0389662855',
    lobby: 'lobby 1',
    shift: 'morning',
    date: '21-05-2024',
    totalTable: 100,
    status: 'paid',
  },
];
const food = [
  {
    order: 1,
    foodName: 'beef',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    foodName: 'beef',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    foodName: 'beef',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    foodName: 'beef',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    foodName: 'beef',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    foodName: 'beef',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    foodName: 'beef',
    price: 100,
    quantity: 2,
    total: 200,
  },
];
const service = [
  {
    order: 1,
    serviceName: 'ballet',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    serviceName: 'ballet',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    serviceName: 'ballet',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    serviceName: 'ballet',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    serviceName: 'ballet',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    serviceName: 'ballet',
    price: 100,
    quantity: 2,
    total: 200,
  },
  {
    order: 1,
    serviceName: 'ballet',
    price: 100,
    quantity: 2,
    total: 200,
  },
];
const lobType = [
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
  {
    id: '#1',
    typeName: 'a',
    maxTable: 50,
    minPrice: 200,
    requiredDeposit: 20,
  },
];
const lobby = [
  {
    lobby_id: 'FgHiJk1-LmNo-2PqRs-3TuVw',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['evening'],
  },
  {
    lobby_id: '#2',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['noon'],
  },
  {
    lobby_id: '#3',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: [],
  },
  {
    lobby_id: '#4',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['noon', 'evening'],
  },
  {
    lobby_id: '#5',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['evening'],
  },
  {
    lobby_id: '#6',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['noon', 'evening'],
  },
  {
    lobby_id: '#7',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['noon', 'evening'],
  },
  {
    lobby_id: '#8',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['noon', 'evening'],
  },
  {
    lobby_id: '#9',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['noon', 'evening'],
  },
  {
    lobby_id: '#10',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['noon', 'evening'],
  },
  {
    lobby_id: '#11',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['noon', 'evening'],
  },
  {
    lobby_id: '#12',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['noon', 'evening'],
  },
  {
    lobby_id: '#13',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['noon', 'evening'],
  },
  {
    lobby_id: '#14',
    lobType: 'a',
    lobName: 'lobby 1',
    bookedShift: ['noon', 'evening'],
  },
];
const foodList = [
  {
    id: '#1',
    name: 'beef',
    price: 200,
  },
  {
    id: '#2',
    name: 'chicken',
    price: 200,
  },
  {
    id: '#3',
    name: 'beef',
    price: 200,
  },
  {
    id: '#4',
    name: 'beef',
    price: 200,
  },
  {
    id: '#5',
    name: 'beef',
    price: 200,
  },
  {
    id: '#6',
    name: 'beef',
    price: 200,
  },
  {
    id: '#7',
    name: 'beef',
    price: 200,
  },
];
const serviceList = [
  {
    id: '#1',
    name: 'ballet',
    price: 200,
  },
  {
    id: '#2',
    name: 'ballet',
    price: 200,
  },
  {
    id: '#3',
    name: 'ballet',
    price: 200,
  },
  {
    id: '#4',
    name: 'ballet',
    price: 200,
  },
  {
    id: '#5',
    name: 'ballet',
    price: 200,
  },
  {
    id: '#6',
    name: 'ballet',
    price: 200,
  },
  {
    id: '#7',
    name: 'ballet',
    price: 200,
  },
];

export { orderList, food, service, lobType, lobby, foodList, serviceList };
